### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by jkwatson-verta** [JetBrains/jetCheck#5]
I would love to try using this, but would greatly prefer a maven-central publication to using jitpack.

Is this project being actively maintained? I haven't seen any activity in nearly a year.

**Comment by donnerpeter** [comment]
Publishing to Maven Central is possible, but can take some time and effort. Why exactly do you disprefer jitpack?

The project is in a "sleeping" state: it works where it's needed, nobody requests anything, so there are no commits. But I can provide some fixes and improvements if necessary.

**Comment by jkwatson-verta** [comment]
> Publishing to Maven Central is possible, but can take some time and effort. Why exactly do you disprefer jitpack?

Just corporate compliance issues. No personal problem with it. :)

**Comment by donnerpeter** [comment]
Does it absolutely need to be Maven Central? Would a repository placed at https://packages.jetbrains.team be also compliant?

**Comment by jkwatson-verta** [comment]
> Does it absolutely need to be Maven Central? Would a repository placed at https://packages.jetbrains.team be also compliant?

That would probably be fine, as long as compliance folks can verify integrity of the source of the code. (and, yeah..this is only for testing, so probably not a huge deal in the long run).

**Comment by donnerpeter** [comment]
(I've not given up on this; I'm trying to figure out how to publish it. Sorry for the delay)

**Comment by donnerpeter** [comment]
It appears to be more complicated than I thought. I've filed https://youtrack.jetbrains.com/issue/IJI-1460/Publish-jetCheck-to-Maven-Central, which you can vote or watch. In the meantime, you could still try the library and find some bugs without committing the test to the repository.

**Comment by jkwatson-verta** [comment]
cool. you can feel free to close this, then. Thanks!

**Comment by DmPanov** [comment]
Finally, we have the 0.2.3 version [live](https://repo1.maven.org/maven2/org/jetbrains/jetCheck/) on Maven Central! Thanks everyone for your patience.
